baseURL = 'https://blog.borber.top/'
languageCode = 'en-us'
title = 'Blog'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-25FBE8WVQQ"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'ä½ å¥½!'
homeIntroContent = """
æˆ‘æ˜¯ä¸€åä¸­å›½è½¯ä»¶å·¥ç¨‹å¸ˆ, ç°å·¥ä½œäºæ·±åœ³, æ‹¥æœ‰æ‰å®çš„è®¡ç®—æœºç§‘å­¦åŸºç¡€å’Œè§£å†³å¤æ‚é—®é¢˜çš„çƒ­æƒ….
æˆ‘å¯¹`rust`, ç½‘ç»œå¼€å‘, å®¢æˆ·ç«¯å¼€å‘ç­‰ä¸€ç³»åˆ—è¯¾é¢˜éƒ½å¾ˆæ„Ÿå…´è¶£.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

footerContent = "All content licensed under CC BY-SA 4.0 license unless otherwise stated. Copyright Â© 2025 ğ˜½ğ™¤ğ™§ğ™—ğ™šğ™§"

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/borber"

[[params.social]]
name = "telegram"
url = "https://t.me/call_borber_bot"

[[params.social]]
name = "mastodon"
url = "https://wxw.moe/deck/@BORBER"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "photo"
url = "/photo"


[[params.menu]]
name = "friends"
url = "/friends"

[[params.menu]]
name = "library"
url = "/library"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
noClasses = false
style = 'algol'

# Giscus comments
[params.giscus]
enable = true
repo = "borber/blog"
repoid = "MDEwOlJlcG9zaXRvcnkyODI5ODY0OTM"
category = "General"
categoryid = "DIC_kwDOEN4H_c4CXmYS"
mapping = "title"
theme = "preferred_color_scheme"


[markup.goldmark.renderer]
unsafe = true
